### ISSUE TITLE
Win checking

### ISSUE THREAD

**Issue by WanZachWN** [ZachWolfy/ECE3220-Final-Project#4]
we also need a win checking function. If not we won't know if the user has won or not.

**Comment by chkz6d** [comment]
I have already done the code

**Comment by chkz6d** [comment]
bool GetWin(Minesweeper& mine)
{
	for (int i = 0; i < mine.ROW; i++)
	{
		for (int j = 0; j < mine.COL; j++)
		{
			if (mine.play_map[i][j] == "-")
			{
				if (mine.ans_map[i][j] != "B")
				{
					return false;
				}
			}
		}
	}
	return true;
}
